name: Portfolio CI

on: [push, pull_request]

jobs: 
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check files
        run: ls -la

      - name: Project info
        run: echo "Portfolio CI running!"

      - name: Show date
        run: date


